version: '3.9'
services:
  db:
    # service/container for the database
    image: postgres
    container_name: toduties_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - toduties_network

  backend:
    build: ./backend
    container_name: toduties_backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - toduties_network
  
  frontend:
    build: ./frontend
    container_name: toduties_frontend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - toduties_network
  
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: test
    container_name: toduties_frontend_test
    depends_on:
      - frontend
    networks:
      - toduties_network
    profiles:
      - test

volumes:
  db_data:
    name: toduties_volume

networks:
  toduties_network:
    name: toduties_network
